### PR TITLE
Fix siren revenge bypass

### PR DESCRIPTION
**Pull request by jebob**
Sirenican focus "revenge" should bypass if already at war

The current bypass looks like
* Must be at war with every surviving equestrian nation
* AND (control canterlot OR allied changelings control canterlot)

It currently doesn't bypass if at war with every surviving equestrian nation but Equestria holds canterlot.

It should look like:
* Must be at war with every surviving equestrian nation
* AND (control canterlot OR allied changelings control canterlot OR an equestrian nation controls canterlot)

Also two tiny typos

I haven't tested this. What is the standard way to test a fix like this?
## Tests
* [ ] Sirenica at peace with EQS owning canterlot doesn't bypass the focus
* [ ] Sirenica at war with EQS owning canterlot does bypass the focus
* [ ] Sirenica at war with EQS with Sirenica owning canterlot bypasses the focus
* [ ] Sirenica at war with EQS with allied Changelings owning canterlot bypasses the focus
* [ ] Sirenica at war with EQS with Nova Griffonia owning canterlot doesn't bypass the focus

### CODE REVIEW

**Comment by Yard1** [comment]
@jebob Unfortunately there are no standardized procedures for testing - in most cases, the easiest way is to either source a save file where an issue can be replicated, or use console commands to quickly arrive at a state where the issue is present (though usage of console commands themselves can create issues, so one has to be careful).

**Comment by BigSaij** [comment]
@jebob The current bypass requirements are intentional as no Equestrian-based nation should be alive and at peace with Sirenalia for the focus to bypass. The primary reason is to ensure that you still must go to war with Equestrian minors even if already owning or the Changelings already owning Canterlot itself. If you would like to bring up suggestions on changes to content in Sirenalia you can do so with me via Discord or alternative methods.

**Comment by jebob** [comment]
Changed the proposed bypass rules and added some proposed tests

**Comment by Yard1** [comment]
@jebob would you mind resubmitting the typo fix in a separate PR? thank you!

**Comment by jebob** [comment]
@Yard1 #1949

**Pull request closed without merging**
